=== ana-polo/LMSGI-RA5-starWars/solucion/DTD/externo/LMSGI-RA4c-Viaje-DTD.dtd
<!--
    Fichero: LMSGI-RA4c-Viaje-DTD.dtd
    Funcionalidad: Ejemplo de dtd para la gestiÃ³n de los ficheros de tipo viaje.xml.

    Autor: Ana Polo Arozamena
    IES Alisal
-->

<!-- ********* -->
<!-- Elementos -->
<!-- ********* -->


<!-- *** Nivel 1 *** -->

<!ELEMENT viaje (etapa+)>

    <!-- *** Nivel 2 *** -->

    <!ELEMENT etapa (lugar, transporte, alojamiento)>


        <!-- *** Nivel 2 *** -->

        <!ELEMENT lugar (#PCDATA)>
        <!ELEMENT transporte (#PCDATA)>
        <!ELEMENT alojamiento (#PCDATA)>


    <!-- ********* -->
    <!-- Atributos -->
    <!-- ********* -->

    <!-- Obligatorios -->

    <!ATTLIST etapa dia CDATA #REQUIRED>

=== ana-polo/LMSGI-RA5-starWars/solucion/DTD/externo/viaje-DTD.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE viaje SYSTEM "LMSGI-RA4c-Viaje-DTD.dtd">


<viaje>
		<etapa dia="10/10/2020">
			<lugar>Aguilar de Campoo</lugar>
			<transporte>autobus</transporte>
			<alojamiento>Casa rural</alojamiento>
		</etapa>

		<etapa dia="11/10/2020">
			<lugar>Cervera de Pisuerga</lugar>
			<transporte>taxi</transporte>
			<alojamiento>Hostal</alojamiento>
		</etapa>

		<etapa dia="12/10/2020">
			<lugar>Potes</lugar>
			<transporte>Blablacar</transporte>
			<alojamiento>Hotel</alojamiento>
		</etapa>
</viaje>
