=== ana-polo/LMSGI-RA5-starWars/solucion/XMLSchema/LMSGI-RA4d-Viajes-XMLSchema-referencia-tipos.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<!-- Definición del vocabulario -->

<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema"
		   elementFormDefault = "qualified" >

    <xs:annotation>
        <xs:documentation xml:lang  = "es-es" >
			<fichero>LMSGI-RA4d-Viajes-XMLSchema-referencia</fichero>
			<fechaCreacion>24-01-2023</fechaCreacion>
			<autor>Ana Polo Arozamena</autor>
			<aplicación>
				Ejemplo de uso de XSD con tipos globales.
			</aplicación>
            <utilidad>Vocabulario para la validación de ficheros básicos para la gestión de viajes</utilidad> 
        </xs:documentation>
    </xs:annotation>

	<!-- ************** -->
	<!-- TIPOS DE DATOS -->
	<!-- ************** -->

	<!-- Definición de tipoTexto30
		 Es una cadena de texto de 30 caracteres.
		 Uso: Todos los elementos terminales.
	-->

	<xs:simpleType name = "tipoTexto30" >
		<xs:restriction base = "xs:string" >
			<xs:maxLength value="30" />
		</xs:restriction>
	</xs:simpleType>



	<!-- ************************** -->
	<!-- Definición del vocabulario -->
	<!-- ************************** -->

	<!-- ********* -->
	<!-- ELEMENTOS -->
	<!-- ********* -->

	<!-- Nivel 1 -->

	<!-- Definición del ejemplar: viaje -->

    <xs:element name = "viaje" >
        <xs:complexType>

			<!-- Declaración de los elementos que forman viaje -->

            <xs:sequence>
				<xs:element ref = "etapa" maxOccurs = "unbounded" />
            </xs:sequence>

			<!-- Fin de la declaración de los elementos que forman viaje -->

		</xs:complexType>
    </xs:element>

	<!-- Fin ejemplar -->


	<!-- Nivel 2 -->

	<!-- Definición de etapa -->

	<xs:element name = "etapa" >
        <xs:complexType>

			<!-- Declaración de los elementos que forman etapa -->

            <xs:sequence>
				<xs:element name = "lugar" type = "tipoTexto30" />
				<xs:element name = "transporte" type = "tipoTexto30"  />
				<xs:element name = "alojamiento" type = "tipoTexto30"  />
            </xs:sequence>

			<!-- Fin de la declaración de los elementos que forman etapa -->

			<!-- Declaración de los atributos que forman etapa -->

			<xs:attribute name = "dia" use = "required" type = "xs:date" />

			<!-- Fin de la declaración de los atributos que forman etapa -->

		</xs:complexType>
    </xs:element>

	<!-- Fin etapa -->

</xs:schema>

<!-- Fin esquema -->

=== ana-polo/LMSGI-RA5-starWars/solucion/XMLSchema/referencia-tipos/viaje-XML-XSD-referencia-tipos.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!-- En la apertura del ejemplar se incluyen los atributos que permiten
	 la validación del documento XML contra el esquema XML-Schema
	 correspondiente.
	 El atributo xmlns:xsi indica que se utilizará el espacio de nombres
	 de XML-Schema para la validación.
	 El atributo xsi:noNamespaceSchemaLocation indica la ruta del esquema
	 XML-Schema que se utilizará para la validación.
	 El atributo standalone indica que el documento XML no es autocontenido.
-->

<viaje xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation = "LMSGI-RA4d-Viajes-XMLSchema-referencia-tipos.xsd" >

	<etapa dia="2022-12-30">
		<lugar>Aguilar de Campoo</lugar>
		<transporte>autobus</transporte>
		<alojamiento>Casa rural</alojamiento>
	</etapa>

	<etapa dia="2022-12-31">
		<lugar>Cervera de Pisuerga</lugar>
		<transporte>taxi</transporte>
		<alojamiento>Hostal</alojamiento>
	</etapa>

	<etapa dia="2022-01-10">
		<lugar>Potes</lugar>
		<transporte>Blablacar</transporte>
		<alojamiento>Hotel</alojamiento>
	</etapa>
</viaje>
